### ISSUE TITLE
Subreddit post collection not working on Mac OS

### ISSUE THREAD

**Issue by eelegiap** [bellingcat/knewkarma#32]
I was wondering how far along this project is, since there appear to be some bugs.

Running the CLI command `knewkarma subreddit <my-subreddit-here> --posts` on the terminal in Mac OS (after pip installing and building dockerfile) does not yield the expected results (a JSON of posts with metadata). I'm on Python 3.11.5. Instead, my JSON looks like this for `knewkarma subreddit OSINT --posts`:

`{
    "kind": "t3",
    "data": {
        "approved_at_utc": null,
        "subreddit": "OSINT",
        "selftext": "This is Rule 1 one the sidebar ....",
        "author_fullname": "t2_clzxs",
        "title": "Requesting help identifying people",
        "link_flair_richtext": [],
        "subreddit_name_prefixed": "r/OSINT",
... ....
        "author_flair_template_id": "85b604bc-ba44-11e9-a54d-0ea6ef118ab6",
      "url": "https://www.reddit.com/r/OSINT/comments/g84lxn/requesting_help_identifying_people/",
        "subreddit_subscribers": 91215,
        "created_utc": 1587860759.0,
        "num_crossposts": 3,
        "media": null,
        "is_video": false
    }
}`

**Comment by rly0nheart** [comment]
Hello @eelegiap , could you use the issue template for me to better understand the issue? :)

**Comment by eelegiap** [comment]
Sorry about the issue formatting there @rly0nheart! I was using knewkarma==2.1.0.0

**Comment by rly0nheart** [comment]
So I found the bug, I will push the patch in a few minutes. Then I'm going to ask you to try running the command again and see if it works

**Comment by rly0nheart** [comment]
> Sorry about the issue formatting there @rly0nheart! I was using knewkarma==2.1.0.0

@eelegiap  I have published a release with a fix for the bug [2.2.0.0](https://pypi.org/project/knewkarma/2.2.0.0). Install this then try again and let me know if it works as expected.

**Comment by eelegiap** [comment]
@rly0nheart Yes, it's working now! Thanks for the quick fix there. I was just wondering -- how far back does the scraper go if I don't specify any limits?

**Comment by rly0nheart** [comment]
> @rly0nheart Yes, it's working now! Thanks for the quick fix there. I was just wondering -- how far back does the scraper go if I don't specify any limits?

The default limit is set to 50 (sometimes might return 53), you can set it to a larger value to see more posts. I figured if you use a value less than 10, you will get an empty list.
