### ISSUE TITLE
CLI Requires Interaction

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/knewkarma#49]
**Describe the bug**

When running the knewkarma CLI, the [`Handlers`](https://github.com/bellingcat/knewkarma/blob/9e7668e87a1d0d188bd502ffdc30542c4699b16f/knewkarma/executor.py#L83) class seems to require interactive input to continue (through use of `Prompt.ask()` and `Confirm.ask()`).

This doesn't match with the default behaviour suggested in the docs, and means that the CLI cannot be run in a non-interative session.

It is a particular issue for `json` and `csv` arguments as there doesn't appear possible to explicitly set them to be false.

**To Reproduce**

`knewkarma --sort new --limit 20 subreddit --posts news`

**Expected behavior**
knewkarma should assume default values for (`sort_criterion, data_limit, json, csv`) and allow the execution to proceed without interaction

**More thoughts**
It might be better for the command to fail than prompt the user for more information.

An explicit `--noninteractive flag` could be one way to allow the user to opt-out of prompting (even if it results in an error message)

**Comment by rly0nheart** [comment]
I noticed that too. It's fixed in the unreleased 3.0 at dev branch. 
I think there's too kuchen cluttered and unnecessary code in the current version. In 3.0 I aim to make the output and code more optimal and readable.

I will leave this issue open until I publish the release.

**Comment by rly0nheart** [comment]
Hey @GalenReich, I just released version 3.0🎉 (release notes [here](https://github.com/bellingcat/knewkarma/releases/tag/3.0.0.0))
